# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nodereal-app:
  podAnnotations:
    team: "frontend"
    biz: "shared"
    appcom: "dcellar-web-ui"
  serviceAccount:
    create: false
    name: ""
  serviceMonitor:
    enabled: false
    monitorPath: /metrics
  configMaps:
    config.yaml:
      data:
        config.yaml: |-
          [Service]
          HTTPListenAddr = "0.0.0.0:8080"
          Concurrency = 0 # no limit
  configMapsMountPath: /app/conf/
  containers:
    env:
      - name: NEXT_PUBLIC_ENV
        value: 'qa'
      - name: NEXT_PUBLIC_GOOGLE_ANALYTICS_ID
        value: 'G-BBP24VWJGR'
      - name: NEXT_PUBLIC_BSC_CHAIN_ID
        value: '97'
      - name: NEXT_PUBLIC_GREENFIELD_CHAIN_ID
        value: '9000'
      - name: NEXT_PUBLIC_BSC_RPC_URL
        value: 'https://data-seed-prebsc-1-s1.binance.org:8545'
      - name: NEXT_PUBLIC_GREENFIELD_CHAIN_RPC_URL
        value: 'https://gnfd-stagenet-fullnode-tendermint-us.bk.nodereal.cc'
      - name: NEXT_PUBLIC_GREENFIELD_CHAIN_EXPLORER_URL
        value: 'https://greenfieldscan-qanet.fe.nodereal.cc'
      - name: NEXT_PUBLIC_BSC_EXPLORER_URL
        value: 'https://testnet.bscscan.com'
      - name: NEXT_PRIVATE_BILLING_API_URL
        value: "https://greenfield-billing-querier.nodereal.link"
      - name: NEXT_PRIVATE_EXPLORER_API_URL
        value: "https://greenfield-explorer-querier.bk.nodereal.cc"
      - name: NEXT_PUBLIC_GREENFIELD_CHAIN_MAINNET_RPC_URL
        value: "https://greenfield-chain-us.bnbchain.org"

    logsMountPath: /opt/app/logs/
  image:
    pullPolicy: Always
    repository: 346509735976.dkr.ecr.us-east-1.amazonaws.com/dcellar-web-ui
    tag: a5fb16cf9a315b1442cadb0df9781fb421f625a7
  replicaCount: 1
  resources:
    limits:
      cpu: "8"
      memory: 16Gi
    requests:
      cpu:   50m
      memory: 200Mi
  service:
    ports:
      - name: http
        port: 3000
        protocol: TCP
        targetPort: 3000
    type: ClusterIP
  ingress:
    enabled: true
    servicePort: 3000
    annotations:
      kubernetes.io/ingress.class: nginx
      external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    hosts:
      - host: demo-preview.bk.nodereal.cc
        paths:
          - /
